feat: add bazzite media mentions
ublue-os/website pull request #397
Opened 2023-08-23 23:31 UTC by castrojo

BAZZITE HAS ARRIVED.

2023-08-23 23:37 UTC, p5 commented on docs/media.md
> +**Techspot**: [Linux desktop users can get the Steam Deck experience with Bazzite]([https://www.gamingonlinux.com/2023/08/bazzite-is-a-new-fedora-based-linux-for-steam-deck-and-gaming-pcs/](https://w
In fact, I think this is meant to be 
```
**Techspot**: [Linux desktop users can get the Steam Deck experience with Bazzite](https://www.techspot.com/news/99902-linux-desktop-users-can-get-steam-deck-experience.html)
```
?

2023-08-23 23:38 UTC, p5 commented on docs/media.md
> +**Techspot**: [Linux desktop users can get the Steam Deck experience with Bazzite]([https://www.gamingonlinux.com/2023/08/bazzite-is-a-new-fedora-based-linux-for-steam-deck-and-gaming-pcs/](https://w
```suggestion
**Techspot**: [Linux desktop users can get the Steam Deck experience with Bazzite](https://www.techspot.com/news/99902-linux-desktop-users-can-get-steam-deck-experience.html)
```

2023-08-23 23:45 UTC, p5 approved these changes
Don't think approving will do anything without contributor, but it's the effort that counts :)

2023-08-24 00:00 UTC, storyaddict requested changes
Idk why, but when I run this locally the last YouTube video is shown twice, despite the URLs being different.

2023-08-24 00:04 UTC, storyaddict approved these changes
Duplicate video seems to have been a cache issue. Resolved after clearing cache. Approved.

2023-08-24 00:05 UTC, merged