fix: SELinux to permissive and added stopping the...
ublue-os/website pull request #423
Opened 2023-09-02 07:24 UTC by nicknamenamenick

Waydroid container after the Google Play Certificate has been added.  It's better practice to have SELinux in permissive mode rather than disabled.  I know this is an upstream bug with SELinux and OCI, but for now it's better to have users just have it set to permissive then to fully disable it.

2023-09-02 07:41 UTC, KyleGospo approved these changes

2023-09-02 14:12 UTC, castrojo requested changes

2023-09-02 14:12 UTC, castrojo commented on docs/images/bazzite/waydroid.md
> +Currently there is an issue with SELinux file re-labeling in OCI images that prevents Waydroid from being used without SELinux being in permissive first.
```suggestion
Currently there is an issue with SELinux file re-labeling in OCI images that prevents Waydroid from being used without SELinux being set to permissive first.
```

2023-09-02 18:55 UTC, fiftydinar commented
I had disabled SELinux on one machine before & I also recommend to never do it again. I couldn't boot to enabled SELinux after some time.

2023-09-03 04:45 UTC, castrojo approved these changes

2023-09-03 17:33 UTC, castrojo approved these changes

2023-09-03 17:36 UTC, merged